### ISSUE TITLE
Create custom EditText class

### ISSUE THREAD

**Issue by MStojkovic** [MStojkovic/dudusgram#14]
Create a custom EditText class that has an overriden method onFocusChanged() that hides the keyboard when focus is lost and sets the cursor at the end when the focus is gained.

**Comment by MStojkovic** [comment]
Would it be better to override the EditText class or create a new class that extends EditText?
@sljubic

**Comment by sljubic** [comment]
Do not understand. Classes are not overridden, methods are.
Anyway, if you want to create your own version of EditText, with the presumption that it will be used on many places afterwards, then you would want to extend EditText.
