### ISSUE TITLE
Comment wrapping

### ISSUE THREAD

**Issue by dinoilic** [MStojkovic/dudusgram#21]
Make comment text box wrap around so it doesn't keep scrolling text horizontally.

**Comment by dinoilic** [comment]
Same thing for wrapping descriptions when adding photos.

**Comment by MStojkovic** [comment]
Fixed in commit: 0462ce07e8a58703f8572ca1c9fb66a47f4f33c6

**Comment by MStojkovic** [comment]
Even betetr fix in commit: 10e15d6d06b44bf22ab90c9530eb399ef927a656
