### ISSUE TITLE
Awful quality when uploading photos from camera

### ISSUE THREAD

**Issue by dinoilic** [MStojkovic/dudusgram#23]
Check my latest photo.

**Comment by MStojkovic** [comment]
Thats just your crappy camera :)

**Comment by dinoilic** [comment]
Pls fix this -- crucial feature

**Comment by dinoilic** [comment]
:)))))

**Comment by MStojkovic** [comment]
https://developer.android.com/training/camera/photobasics.html

**Comment by dgranosa** [comment]
@dinoilic why are you like this ?

**Comment by MStojkovic** [comment]
Fixed in:cc508d56337dc3d51846415b72de7431b4308ecc
