### ISSUE TITLE
Wrong user when checking comments

### ISSUE THREAD

**Issue by dinoilic** [MStojkovic/dudusgram#26]
When I check comments of my photo I see different user as the author.

![Screenshot_20190524-184011](https://user-images.githubusercontent.com/4788533/58343533-8c22ff80-7e53-11e9-988c-5d87c3fdc8cb.png)

**Comment by MStojkovic** [comment]
Fixed in commit: b49f7ca4c65e7828c11db18045111414dd0dd154
