### ISSUE TITLE
Input2

### ISSUE THREAD

**Issue by MStojkovic** [MStojkovic/dudusgram#4]
When the user clicks on a edittext, put the cursor at the end.

**Comment by sljubic** [comment]
None of this actually works?
https://stackoverflow.com/questions/6217378/place-cursor-at-the-end-of-text-in-edittext

**Comment by MStojkovic** [comment]
Sadly no.
 et.setSelection(et.getText().length()); -> puts the cursor at the end only for a split second, but then it switches back to where the user pressed. Seems like something is overriding it, but I don't know what.
append("") also doesnt work.

**Comment by sljubic** [comment]
Even if you wrap setSelection call in new runnable via post?

**Comment by MStojkovic** [comment]
That seems to work. Thank you for your help.
